### ISSUE TITLE
Need to recheck format of MAC address in flow control directed address

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#118]
```yml
directed_address:
          description: "The 48bit mac address that the layer1 port names will listen\
            \ on for a directed pause.  "
          type: string
          default: 0180C2000001
```
