### ISSUE TITLE
Remove all usage of nullable in API spec

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#165]
We still have some places in models where we use `nullable`.
e.g.
```yaml
 multi_exit_discriminator:
          description: >-
            The multi exit discriminator (MED) value. 
            A null value means the MED feature is not enabled.
          type: integer
          default: 0
          nullable: true
```

`nullable` is explicitly ruled out of modelling guide because its use overlaps with required/optional fields.
 
e.g. think about user (the one who’s creating data models) specifying a property as “optional” and setting “nullable=False”.
 
I think for this reason, in latest OpenAPI spec, it was removed.
See: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#dataTypes
