### ISSUE TITLE
Support enumeration and filtering of flows

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/models#230]
# Flow Metrics Enumeration and Filtering

A model for flow metrics enumeration and filtering which allows a user to
break enumerate a flow by identifying items of interest such as fields in the
flow as it enters a system under test (ingress), fields in the flow as it exits the
system under test (egress), transmit ports and transmit/receive port pairs.  
The model should be flexible enough to allow for future expansion.

- flow metric group configuration
- flow metric group request
- flow metric group response

## Test

1. Send a single flow of eth+vlan+ipv4 and receive eth+ipv4.
2. Expect dut to strip vlan and inject the correct ethernet type.
3. Get flow metrics enumerated by ingress ethernet source ip address and egress ethernet type.

## Configuration

1. Add unique name to packet ethernet src field.
2. Add unique name to egress_packet ethernet type field.
3. Add ingress item to flow metric groups.
4. Add egress item to flow metric groups.

## Metrics

1. Request specific flow, metric groups and metrics.
2. Response for the specific request should include metrics for the flow and any requested metric groups that have been configured.

## set_config (request) APPROACH 1 (metric_group name)

```yaml
flow:
  name: f1
  packet: # describe the shape of the packet as it exits the otg system enters the system under test
    ethernet:
      src:
        metric_group: f1-eth-src # provide a unique name for the field so that it can be referenced in flow.metrics
    vlan:
    ipv4:
  egress_packet: # describe the shape of the packet as it exits the system under test and enters the otg system
    ethernet:
      ether_type:
        metric_group: f1-eth-type # provide a name for the field so that it can be referenced in flow.metrics
  metrics:
    enable: true
    metric_groups: # configuration container for all metric groups
      ingresses:
        - field_name: f1-eth-src
      egresses:
        - field_name: f1-eth-type
          field_offset: 0
          field_length: 16
```

## set_config (request) APPROACH 2 (nested metric_group)

```yaml
flow:
  name: f1
  packet: # describe the shape of the packet as it exits the otg system enters the system under test
    ethernet:
      src:
        metric_group: 
          name: f1-eth-src 
    vlan:
    ipv4:
  egress_packet: # describe the shape of the packet as it exits the system under test and enters the otg system
    ethernet:
      ether_type:
        metric_group: 
          name: f1-eth-type 
          field_offset: 0
          field_length: 16
  metrics:
    enable: true
```

## get_metrics (request)

```yaml
flow:
  flow_names: [f1]
  metric_names: [frames_tx, frames_rx]
  metric_groups:
    - name: f1-eth-src
    - name: f1-eth-type
      filters:
        - hex_value: 0xffff
```

## get_metrics (response)

```yaml
flow:
  - name: f1
    frames_tx: 2322
    frames_rx: 2322
    metric_groups:
      - name: f1-eth-src
        frames_tx: 2322
        frames_rx: 2322
      - name: f1-eth-type
        frames_tx: 2322
        frames_rx: 2322
        filters:
          - value: 0xffff
            frames_tx: 2322
            frames_rx: 2322
```

**Comment by ajbalogh** [comment]
@ANISH-GOTTAPU @ashutshkumr soliciting you for comments.
The above reduces the code generated but requires two steps to configure, setting the name and referencing it the flow.metrics.
The other approach would be to generate an ingress/egress metric group schema object for every field.

**Comment by ANISH-GOTTAPU** [comment]
@ajbalogh : I like the approach 1 instead of nested metric group. 

Do we need `egress_packet` ? As the ingress and egress reference field names are provided under `ingresses` and `egresses` 

Model without `egress_packet` would be like this
```
flow:
  name: f1
  packet: # describe the shape of the packet as it exits the otg system enters the system under test
    ethernet:
      src:
         metric_group: f1-eth-src # provide a unique name for the field so that it can be referenced in flow.metrics
      ether_type:
         metric_group: f1-eth-type
    vlan:
    ipv4:
  metrics:
    enable: true
    metric_groups: # configuration container for all metric groups
      ingresses:
        - field_name: f1-eth-src
      egresses:
        - field_name: f1-eth-type
          field_offset: 0
          field_length: 16
```
