### ISSUE TITLE
Duration & Burst parameters need to be int64

### ISSUE THREAD

**Issue by ankur-sheth** [open-traffic-generator/models#292]
```
   Flow.FixedPackets:
      description: |-
        Transmit a fixed number of packets after which the flow will stop.
      type: object
      properties:
        packets:
          description: |-
            Stop transmit of the flow after this number of packets.
          type: integer
          minimum: 1
          default: 1
...
          x-field-uid: 1
        packets:
          description: |-
            The number of packets transmitted per burst.
          type: integer
          minimum: 1
          default: 1
          x-field-uid: 2

```

We need to be able to send >2^32 packets in a flow when configured when `duration` is configured as `fixed_packets` or `burst`.
