### ISSUE TITLE
Line rate should accept float value

### ISSUE THREAD

**Issue by indraniBh** [open-traffic-generator/models#43]
Now line rate should be of type integer. But in some cases we need to provide line rate less than 1.

**Comment by ajbalogh** [comment]
line rate in Flow.Rate is now modeled as a number which allows for floats

```
        percentage:
          description: >-
            The percentage of a port location's available bandwidth.
          type: number
```
