### ISSUE TITLE
Delay in burst duration

### ISSUE THREAD

**Issue by indraniBh** [open-traffic-generator/models#75]
@ajbalogh 
"delay" field is missing in "burst" duration.
Also, for rest of the choices (fixed_packets, fixed_seconds, continuous and burst) for the field of "gap", don't we have to mention the gap unit?

**Comment by ajbalogh** [comment]
```
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
```
